
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class city
{

    public int Id { get; set; }

    public string Name { get; set; }

    public Nullable<int> Population { get; set; }

    public string Mayor { get; set; }

    public string country_code { get; set; }



    public virtual country country { get; set; }

}

}
