
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class country
{

    public country()
    {

        this.cities = new HashSet<city>();

    }


    public string Code { get; set; }

    public string Name { get; set; }

    public Nullable<int> Population { get; set; }

    public string Continent { get; set; }

    public Nullable<System.DateTime> established { get; set; }



    public virtual ICollection<city> cities { get; set; }

}

}
