
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class department
{

    public int dept_id { get; set; }

    public string dept_name { get; set; }

    public string dept_description { get; set; }

    public string dept_extension { get; set; }

    public Nullable<System.DateTime> date_added { get; set; }

    public int site_id { get; set; }



    public virtual site site { get; set; }

}

}
