
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class faq
{

    public int id { get; set; }

    public string question { get; set; }

    public string answer { get; set; }

    public Nullable<System.DateTime> date_created { get; set; }

    public int publisher_id { get; set; }

    public int category_id { get; set; }



    public virtual category category { get; set; }

    public virtual user user { get; set; }

}

}
