
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class feedback
{

    public int feedback_id { get; set; }

    public Nullable<int> user_id { get; set; }

    public string date_location { get; set; }

    public string suggestion { get; set; }

    public string detail { get; set; }

    public string problem { get; set; }

    public System.DateTime date_submitted { get; set; }

}

}
