

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class NSHNContext : DbContext
{
    public NSHNContext()
        : base("name=NSHNContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<province> provinces { get; set; }

    public DbSet<role> roles { get; set; }

    public DbSet<user> users { get; set; }

    public DbSet<image> images { get; set; }

    public DbSet<news> news { get; set; }

    public DbSet<comment> comments { get; set; }

    public DbSet<bucketList> bucketLists { get; set; }

    public DbSet<city> cities { get; set; }

    public DbSet<country> countries { get; set; }

    public DbSet<Images_Table> Images_Table { get; set; }

    public DbSet<message> messages { get; set; }

    public DbSet<category> categories { get; set; }

    public DbSet<department> departments { get; set; }

    public DbSet<site> sites { get; set; }

    public DbSet<feedback> feedbacks { get; set; }

    public DbSet<AvailableTest> AvailableTests { get; set; }

    public DbSet<LabTestResult> LabTestResults { get; set; }

    public DbSet<LabTestsConducted> LabTestsConducteds { get; set; }

    public DbSet<database_firewall_rules> database_firewall_rules { get; set; }

    public DbSet<Tour> Tours { get; set; }

    public DbSet<faq> faqs { get; set; }

    public DbSet<TourGuide> TourGuides { get; set; }

    public DbSet<TourRequest> TourRequests { get; set; }

    public DbSet<Volunteer> Volunteers { get; set; }

    public DbSet<appointment> appointments { get; set; }

    public DbSet<donation> donations { get; set; }

    public DbSet<north_shore_accounts> north_shore_accounts { get; set; }

    public DbSet<payment_information> payment_information { get; set; }

}

}

