
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TourGuide
{

    public int GuideID { get; set; }

    public string GuideName { get; set; }

    public string GuideSpeciality { get; set; }

    public string GuideSuitability { get; set; }

}

}
