
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Volunteer
{

    public int VolunteerID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime Dob { get; set; }

    public string Phone { get; set; }

    public string StAddress { get; set; }

    public string Reason { get; set; }

    public string skills { get; set; }

    public string username { get; set; }

    public string Email { get; set; }

    public System.DateTime dateavailable { get; set; }

}

}
